### ISSUE TITLE
How is this an omx rpi version?

### ISSUE THREAD

**Issue by iamogopogo** [reversegear/scrcpy-pi-omx#2]
Reading your how to, and it says to build and install the generic scrcpy, then to run your startscreen.sh...but nowhere does it include the omx library. Palazzoni built his server with the omx library, making it an omx-rpi-scrcpy.

Am I missing something?

**Comment by reversegear** [comment]
this script uses omx-player

**Comment by iamogopogo** [comment]
So it's not an actual omx build then, therefore it's not optimized to use the omx library. It's just the regular scrcpy...piped to the omxplayer. An omx build adds the hardware encoding...otherwise, it's still software encoding...ie: slow. FFmpeg needs to be built with ' --enable-mmal --enable-omx --enable-omx-rpi' in order to use the hardware encoding/acceleration, but scrcpy will not build using that ffmpeg, complaining about not finding libraries.

**Comment by reversegear** [comment]
> 
> 
> So it's not an actual omx build then, therefore it's not optimized to use the omx library. 

this is what it says

> Android screemirror with scrcpy and omxplayer on RPi

> FFmpeg needs to be built with ' --enable-mmal --enable-omx --enable-omx-rpi' in order to use the hardware encoding/acceleration

refer [this ](https://github.com/Genymobile/scrcpy/issues/273#issuecomment-513895917)

**Comment by iamogopogo** [comment]
> this is what it says
> 
> > Android screemirror with scrcpy and omxplayer on RPi

Crap...that obviously went over my head...my bad.

> refer [this ](https://github.com/Genymobile/scrcpy/issues/273#issuecomment-513895917)

Yeah, that's the original thread I came across. I can build scrcpy using the generic ffmpeg, but after enabling omx and omx-rpi, ninja complains it can't find 3 specific libraries that I know exist. I then tried loading the libraries, but it only accepted them 1 at a time, not all 3 at once...so I was stuck in a loop. But along the way, I discovered you can use 'adb exec-out screenrecord' to do what scrcpy does, and since I can build the omx optimized ffmpeg already, I'm about to try on a fresh image and ffmpeg build. The thread I came across had the guy piping that to ffplay, and another thread had it piped to VLC. If it works, then that's all I need. :)
